# MIDI Standards - number of pulses in each

MIDI_THIRTYSECOND_NOTE = 3
MIDI_SIXTEENTH_NOTE = 6
MIDI_EIGHTH_NOTE = 12
MIDI_QUARTER_NOTE = 24
MIDI_HALF_NOTE = 48
MIDI_NOTE = 96

# Instrument MIDI channels
# Note: Channels are 0-indexed in mido, but often 1-indexed in casual conversation.
# We will store them as 0-indexed integers here (0-15).

MIDI_CHANNEL_MATRIARCH = 0
MIDI_CHANNEL_STREICHFETT_STRINGS = 1
MIDI_CHANNEL_STREICHFETT_SOLO = 2
MIDI_CHANNEL_MODEL_D = 3
MIDI_CHANNEL_VOCE_EP = 6
MIDI_CHANNEL_DRM1 = 9  # Channel 10 is index 9

# Instrument MIDI Notes

DRM1_MKIV_KICK = 36
DRM1_MKIV_DRUM_1 = 45
DRM1_MKIV_DRUM_2 = 50
DRM1_MKIV_MULTI = 56
DRM1_MKIV_SNARE = 38
DRM1_MKIV_HH1_CLOSED = 44
DRM1_MKIV_HH1_OPEN = 46
DRM1_MKIV_HH2_CLOSED = 49
DRM1_MKIV_HH2_OPEN = 51
DRM1_MKIV_CLAP = 39
